/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_STATE_SECRET": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "GITHUB_WEBHOOK_SECRET": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "MyApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Neon": {
      "connectionUri": string
      "connectionUriPooler": string
      "type": "neon.index/project.Project"
    }
    "Redis": {
      "token": string
      "type": "upstash.index/redisDatabase.RedisDatabase"
      "url": string
    }
    "WEB_SESSION_SECRET": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "Web": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}

import "sst"
export {}